image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

build:
  stage: build
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.apsplus.si:5000
  - docker version
  - docker info
  script:
  - docker build -f eslog2_0/Dockerfile -t "$CI_REGISTRY_IMAGE:latest" .
  - docker push $CI_REGISTRY_IMAGE:latest
  tags:
  - docker 

  
deploy_azure:
  stage: deploy
  before_script: 
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.apsplus.si:5000
  script:
    - docker pull "$CI_REGISTRY_IMAGE:latest"
    - docker tag "$CI_REGISTRY_IMAGE" apscontainerregistry.azurecr.io/eslog20
    - docker login -u apscontainerregistry -p bY3thmVnJKV+3D3sCL6gNxadoaKeonmq apscontainerregistry.azurecr.io
    - docker push apscontainerregistry.azurecr.io/eslog20
  when: manual
  tags:
    - shell
